/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeodevi;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.util.*;
import java.io.*;
import java.text.DecimalFormat;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Font;
import javax.swing.SwingConstants;
import javax.swing.JButton;
import javax.swing.JFrame;

public class NerdleGUI extends javax.swing.JFrame {
	public static String guess ="";
	public static String[][] guess_all;
	public int index = 0;
	static JLabel[][] liste;
	public static int row=0;
	static int second = 0, minute = 0;
	String ddSecond, ddMinute;
	Timer timer;
	public static DecimalFormat dFormat = new DecimalFormat("00");
	
	public NerdleGUI() {
		initComponents();
        liste = addLabels();
        int len = NerdleGame.getLength();
        switch(len) {
        case 7:
        	jLabel30.setVisible(false);
            jLabel33.setVisible(false);
            jLabel35.setVisible(false);
            jLabel36.setVisible(false);
            jLabel45.setVisible(false);
            jLabel51.setVisible(false);
            
            
            jLabel31.setVisible(false);
            jLabel32.setVisible(false);
            jLabel34.setVisible(false);
            jLabel44.setVisible(false);
            jLabel50.setVisible(false);
            jLabel52.setVisible(false);
            break;
        case 8:
        	jLabel31.setVisible(false);
            jLabel32.setVisible(false);
            jLabel34.setVisible(false);
            jLabel44.setVisible(false);
            jLabel50.setVisible(false);
            jLabel52.setVisible(false);
            break;
        case 9:
        	break;
        }
	}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("3");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="3";
                	}
            	return;
        	}
        });
        jButton4 = new javax.swing.JButton();
        jButton4.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("2");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="2";
                	}
            	return;
        	}
        });
        jButton5 = new javax.swing.JButton();
        jButton5.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("6");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="6";
                	}
            	return;
        	}
        });
        jButton6 = new javax.swing.JButton();
        jButton6.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("5");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="5";
                	}
            	return;
        	}
        });
        jButton7 = new javax.swing.JButton();
        jButton7.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("4");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="4";
                	}
            	return;
        	}
        });
        jButton8 = new javax.swing.JButton();
        jButton8.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("9");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="9";
                	}
            	return;
        	}
        });
        jButton9 = new javax.swing.JButton();
        jButton9.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("8");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="8";
                	}
            	return;
        	}
        });
        jButton10 = new javax.swing.JButton();
        jButton10.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
        		liste[row][index].setText("7");
        		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
        		liste[row][index].setVerticalAlignment(JLabel.CENTER);
            	index++;
            	guess+="7";
            	}
        	return;
        	}
        });
        jButton11 = new javax.swing.JButton();
        jButton11.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("0");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="0";
                	}
            	return;
        	}
        });
        jButton12 = new javax.swing.JButton();
        jButton12.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("+");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="+";
                	}
            	return;
        	}
        });
        jButton13 = new javax.swing.JButton();
        jButton13.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("-");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="-";
                	}
            	return;
        	}
        });
        jButton14 = new javax.swing.JButton();
        jButton14.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("=");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="=";
                	}
            	return;
        	}
        });
        jButton15 = new javax.swing.JButton();
        jButton15.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("*");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="*";
                	}
            	return;
        	}
        });
        jButton16 = new javax.swing.JButton();
        jButton16.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int a = NerdleGame.getLength();
        		if(index!=a) {
            		liste[row][index].setText("/");
            		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
            		liste[row][index].setVerticalAlignment(JLabel.CENTER);
                	index++;
                	guess+="/";
                	}
            	return;
        	}
        });
        jButton17 = new javax.swing.JButton();
        jButton17.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		if(guess.length() == NerdleGame.getLength()) {
        			NerdleGame.setUserEquation(guess);
        			int colors[] = NerdleGame.checkGuess();
        			
        			for(int i=0;i<NerdleGame.getLength();i++) {
        				switch(colors[i]) {
        				case 0:
        					liste[row][i].setBackground(Color.red);
        					break;
        				case 1:
        					liste[row][i].setBackground(Color.yellow);
        					break;
        				case 2:
        					liste[row][i].setBackground(Color.green);
        					break;
        				}
        				
        			}
        			endGame();
        			guess="";
            		row++;
            		index=0;
        		}
        		return;
        	}
        });
        jButton18 = new javax.swing.JButton();
        jButton18.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
            	try {
            		File yarimkalan_f = new File("yarimkalan.txt");
            		File nexttime_f = new File("devamsuresi.txt");
                	boolean x = yarimkalan_f.createNewFile();
                	nexttime_f.createNewFile();
                	FileWriter devamsuresi_w = new FileWriter("devamsuresi.txt");
        			int sure_next = (60*minute)+second;
        			devamsuresi_w.write(sure_next);
        			devamsuresi_w.close();
        			
            		if(x) {
            			FileWriter yarimkalan_w = new FileWriter("yarimkalan.txt");
            			yarimkalan_w.write(1);
              			yarimkalan_w.close();
            		}
            		else {
                			FileReader yarimkalan_r = new FileReader("yarimkalan.txt");
                			int y = yarimkalan_r.read();
                			y++;
                			FileWriter yarimkalan_w = new FileWriter("yarimkalan.txt");
                			yarimkalan_w.write(y);
                			yarimkalan_w.close();
                			yarimkalan_r.close();
            		}
            	}
            	catch(Exception a) {
            		a.printStackTrace();
            	}

        		SaveWrite();
        		dispose();
        		System.exit(1);
        	}
        });
        jButton19 = new javax.swing.JButton();
        jButton19.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		//sil
        		int a = guess.length();
        		if(a==0) {
        			return;
        			}
        		else {
        		guess = guess.substring(0,a-1);
        		a = guess.length();
        		liste[row][a].setBackground(Color.white);
        		liste[row][a].setText("");
        		index = guess.length();
        		//System.out.println("\n index = "+index+" guess = "+guess);
        		return;
        			}
        	}
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Yeni Oyun");
        jButton1.setVisible(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        JLabel lblNewLabel_1 = new JLabel("Mehmet \u015Eadi \u00D6zcan - 20011037");
        lblNewLabel_1.setFont(new Font("Arial", Font.BOLD, 11));
        
        JLabel lblNewLabel_2 = new JLabel("00:00");
        lblNewLabel_2.setFont(new Font("Arial", Font.BOLD, 20));
        timer = new Timer(1000, new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				second++;
				
				ddSecond = dFormat.format(second);
				ddMinute = dFormat.format(minute);				
				lblNewLabel_2.setText(ddMinute+":"+ddSecond);
				
				if(second==60) {
					second=0;
					minute++;
					
					ddSecond = dFormat.format(second);
					ddMinute = dFormat.format(minute);
					lblNewLabel_2.setText(ddMinute+":"+ddSecond);
				}
			}
		});
        timer.start();
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
        			.addComponent(lblNewLabel_2, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        			.addGap(28)
        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblNewLabel_1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        				.addGroup(Alignment.LEADING, jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        					.addComponent(lblNewLabel_2, GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        
        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel30.setOpaque(true);

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel31.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(35)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel30, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel31, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addGap(19))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        				.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        				.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        				.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        				.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        				.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        				.addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        				.addComponent(jLabel30, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        				.addComponent(jLabel31, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel3.setLayout(jPanel3Layout);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setOpaque(true);

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel33.setOpaque(true);

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel32.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel33, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel32, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel33, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel32, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel12, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel13, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel15, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel14, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel22.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel21.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setOpaque(true);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel18.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.setOpaque(true);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel20.setOpaque(true);

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel34.setOpaque(true);

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel35.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel22, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel35, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel34, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel17, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel18, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel22, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel21, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel16, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel19, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel20, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel35, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel34, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel23.setOpaque(true);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel26.setOpaque(true);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel27.setOpaque(true);

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel29.setOpaque(true);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel24.setOpaque(true);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel25.setOpaque(true);

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel28.setOpaque(true);

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel44.setOpaque(true);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel36.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel28, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel27, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel29, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel36, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel44, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel28, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel27, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel23, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel25, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel26, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel24, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel29, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel36, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel44, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel60.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel60.setOpaque(true);

        jLabel61.setBackground(new java.awt.Color(255, 255, 255));
        jLabel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel61.setOpaque(true);

        jLabel62.setBackground(new java.awt.Color(255, 255, 255));
        jLabel62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel62.setOpaque(true);

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel47.setOpaque(true);

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel46.setOpaque(true);

        jLabel63.setBackground(new java.awt.Color(255, 255, 255));
        jLabel63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel63.setOpaque(true);

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel48.setOpaque(true);

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel50.setOpaque(true);

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel45.setOpaque(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel46, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel47, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel48, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel60, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel61, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel62, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel63, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel45, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel50, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel46, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel47, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel48, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel60, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel61, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel62, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel63, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel45, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel50, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );
        
        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel40.setOpaque(true);

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel41.setOpaque(true);

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel43.setOpaque(true);

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel38.setOpaque(true);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel37.setOpaque(true);

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel39.setOpaque(true);

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel42.setOpaque(true);

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel52.setOpaque(true);

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel51.setOpaque(true);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel43, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel39, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel37, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel42, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel38, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel41, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel40, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel51, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
    			.addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jLabel52, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jLabel43, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel39, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel37, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel42, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel38, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel41, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel40, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel51, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel52, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setText("NERDLE");

        jButton2.setText("1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");

        jButton4.setText("2");

        jButton5.setText("6");

        jButton6.setText("5");

        jButton7.setText("4");

        jButton8.setText("9");

        jButton9.setText("8");

        jButton10.setText("7");

        jButton11.setText("0");

        jButton12.setText("+");

        jButton13.setText("-");

        jButton14.setText("=");

        jButton15.setText("*");

        jButton16.setText("/");

        jButton17.setText("Tahmin Et");

        jButton18.setText("Sonra Bitir");

        jButton19.setText("Sil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton19)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        
        lblNewLabel = new JLabel("");
        lblNewLabel.setText("Answer: "+NerdleGame.equation);
        lblNewLabel.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(24)
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(jPanel8, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPanel7, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPanel6, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPanel5, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPanel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPanel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        					.addContainerGap())
        				.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	NerdleGame.generateEquation();
        NerdleGUI yenigui = new NerdleGUI();
        yenigui.minute = 0;
        yenigui.second = 0;
        yenigui.row = 0;
        yenigui.setVisible(true);
        dispose();
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //BUTON 1
    	int a = NerdleGame.getLength();
    	if(index!=a) {
    		liste[row][index].setText("1");
    		liste[row][index].setHorizontalAlignment(JLabel.CENTER);
    		liste[row][index].setVerticalAlignment(JLabel.CENTER);
        	index++;
        	guess+="1";
        	}
    	return;
    	
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NerdleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NerdleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NerdleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NerdleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NerdleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private JLabel lblNewLabel;
    
    public JLabel[][] addLabels() {
    	JLabel liste[][] = new JLabel[6][9];
    	liste[0][0] = jLabel2;
    	liste[0][1] = jLabel3;
    	liste[0][2] = jLabel4;
    	liste[0][3] = jLabel5;
    	liste[0][4] = jLabel6;
    	liste[0][5] = jLabel8;
    	liste[0][6] = jLabel7;
    	liste[0][7] = jLabel30;
    	liste[0][8] = jLabel31;
    	liste[1][0] = jLabel9;
    	liste[1][1] = jLabel10;
    	liste[1][2] = jLabel11;
    	liste[1][3] = jLabel12;
    	liste[1][4] = jLabel13;
    	liste[1][5] = jLabel14;
    	liste[1][6] = jLabel15;
    	liste[1][7] = jLabel33;
    	liste[1][8] = jLabel32;   	
    	liste[2][0] = jLabel17;
    	liste[2][1] = jLabel18;
    	liste[2][2] = jLabel22;
    	liste[2][3] = jLabel21;
    	liste[2][4] = jLabel16;
    	liste[2][5] = jLabel19;
    	liste[2][6] = jLabel20;
    	liste[2][7] = jLabel35;
    	liste[2][8] = jLabel34;
    	liste[3][0] = jLabel28;   	
    	liste[3][1] = jLabel27;
    	liste[3][2] = jLabel23;
    	liste[3][3] = jLabel25;
    	liste[3][4] = jLabel26;
    	liste[3][5] = jLabel24;
    	liste[3][6] = jLabel29;
    	liste[3][7] = jLabel36;
    	liste[3][8] = jLabel44;
    	liste[4][0] = jLabel46;
    	liste[4][1] = jLabel47;   	
    	liste[4][2] = jLabel48;
    	liste[4][3] = jLabel60;
    	liste[4][4] = jLabel61;
    	liste[4][5] = jLabel62;
    	liste[4][6] = jLabel63;
    	liste[4][7] = jLabel45;
    	liste[4][8] = jLabel50;
    	liste[5][0] = jLabel43;
    	liste[5][1] = jLabel39;    	
    	liste[5][2] = jLabel37;   	
    	liste[5][3] = jLabel42;
    	liste[5][4] = jLabel38;
    	liste[5][5] = jLabel41;
    	liste[5][6] = jLabel40;
    	liste[5][7] = jLabel51;
    	liste[5][8] = jLabel52;
    	return liste;
    }
    
    public void endGame() {
    	File basarili_f = new File("basarili.txt");
    	File basarisiz_f = new File("basarisiz.txt");
    	File row_f = new File("row.txt");
    	File bitissuresi_f = new File("bitissuresi.txt");
    	
    	try {
    		boolean x = basarili_f.createNewFile();
    		basarisiz_f.createNewFile();
    		row_f.createNewFile();
    		bitissuresi_f.createNewFile();
    		if(x) {
    			FileWriter basarili_w = new FileWriter("basarili.txt");
    			FileWriter basarisiz_w = new FileWriter("basarisiz.txt");
    			FileWriter row_w = new FileWriter("row.txt");
    			FileWriter bitiss_w = new FileWriter("bitissuresi.txt");
    			
    			basarili_w.write(0);
    			basarisiz_w.write(0);
    			row_w.write(0);
    			bitiss_w.write(0);

    			basarili_w.close();
    			basarisiz_w.close();
    			row_w.close();
    			bitiss_w.close();
    		}
    	}
    	catch(Exception e) {
    		e.printStackTrace();
    	}

    	if(row+1==6 || guess.equals(NerdleGame.equation)) {
    		jPanel2.setVisible(false);
    		lblNewLabel.setVisible(true);
    		if(guess.equals(NerdleGame.equation)) {
    			lblNewLabel.setText("Bildiniz! Cevap: "+NerdleGame.equation);
    			jButton1.setVisible(true);
    			try {
    				FileReader basarili_r = new FileReader("basarili.txt");
    				int bas = basarili_r.read();
    				bas++;
    				FileWriter basarili_w = new FileWriter("basarili.txt");
    				basarili_w.write(bas);
    				basarili_r.close();
    				basarili_w.close();
    				FileReader row_r = new FileReader("row.txt");
    				int x = row_r.read();
    				x = (int)(((bas-1)*x+(row+1))/bas);
    				FileWriter row_w = new FileWriter("row.txt");
        			row_w.write(x);
        			row_r.close();
        			row_w.close();
        			
        			FileReader bitis_r = new FileReader("bitissuresi.txt");
        			int y = bitis_r.read();
        			int sure = (minute*60)+second;
        			y = (int)(((bas-1)*y+sure)/bas);
        			FileWriter bitis_w = new FileWriter("bitissuresi.txt");
        			bitis_w.write(y);
        			bitis_w.close();
        			bitis_r.close();
        			timer.stop();
    				}
    			catch(Exception e) {
    				e.printStackTrace();
    			}
    			return;
    		}
    		if((row+1)==6)
    			lblNewLabel.setText("Bilemediniz. Cevap: "+NerdleGame.equation);
    			jButton1.setVisible(true);
    			try {
    				FileReader basarisiz_r = new FileReader("basarisiz.txt");
    				int bas2 = basarisiz_r.read();
    				bas2++;
    				FileWriter basarisiz_w = new FileWriter("basarisiz.txt");
    				basarisiz_w.write(bas2);;
    				basarisiz_r.close();
    				basarisiz_w.close();
					}
    			catch(Exception e) {
    				e.printStackTrace();
    			}
    		}
    }
    
    public static void SaveWrite(){
    	File eq_file = new File("equation.txt");
    	File usereq_file = new File("userequation.txt");
    	String[][] writing = new String[row][NerdleGame.getLength()];
    	for(int i=0;i<row;i++) {
    		for(int j=0;j<NerdleGame.getLength();j++) {
    			writing[i][j] = liste[i][j].getText();
    			}
    	}
    	
    	try {
    		FileWriter write = new FileWriter("equation.txt");
    		FileWriter writeus = new FileWriter("userequation.txt");
    		write.write(NerdleGame.equation);
    		for(int i=0;i<6;i++) {
        		for(int j=0;j<NerdleGame.getLength();j++) {
        			if(i<row)
        				writeus.write(writing[i][j]);
        			if(i==row || i>row)
        				writeus.write('c');;
        			}
        		}
    		write.close();
    		writeus.close();
    	}
    	catch(IOException e) {
    		e.printStackTrace();
    	}
    }

    public static String[][] SaveRead() {
    	File f1 = new File("equation.txt");
    	File f2 = new File("userequation.txt");
    	char[] eq = new char[(int)f1.length()];
    	String[][] usereq = new String[6][9];
    	char[][] usereq_char = new char[6][9];
    	try {
    		FileReader read = new FileReader("equation.txt");
    		FileReader readus = new FileReader("userequation.txt");
			read.read(eq);
			NerdleGame.setEquation(String.valueOf(eq));
	    	for(int i = 0 ; i<6 ; i++) {
				for(int j = 0 ; j<NerdleGame.getLength() ; j++) {
						usereq_char[i][j] = (char)readus.read();
						usereq[i][j] = String.valueOf(usereq_char[i][j]);
						if(usereq_char[i][j]=='c')
							usereq[i][j]="";
						else if(j+1==NerdleGame.getLength())
							row++;
					}
	    }
	    	read.close();
	    	readus.close();
    	}
    	catch(IOException e) {
    		e.printStackTrace();
    	}
    	
    	return usereq;
    }
    
    public static void colorLabels() {
		char[] denklem = new char[54];
		try {
			FileReader read = new FileReader("userequation.txt");
			read.read(denklem);
		}
		catch(IOException e) {
			e.printStackTrace();
		}
		
		for(int i = 0; i<row; i++) {
			String tahmin = String.valueOf(denklem);
			tahmin = tahmin.substring(i*NerdleGame.getLength(), (i*NerdleGame.getLength()+(NerdleGame.getLength())));
			NerdleGame.setUserEquation(tahmin);
			int dizi[] = new int[NerdleGame.getLength()];
			dizi = NerdleGame.checkGuess();
			
			
			for(int k=0;k<NerdleGame.getLength();k++) {
				switch(dizi[k]) {
				case 0:
					liste[i][k].setBackground(Color.red);
					break;
				case 1:
					liste[i][k].setBackground(Color.yellow);
					break;
				case 2:
					liste[i][k].setBackground(Color.green);
					break;
				}
				
			}

			}
		}
    
    public static void setGuess(String s) {
    	guess = s;
    }         
}